#To run: python text_jackknifing_half_to_fasta.py

#This python script will randomize a txt file formatted as such:
#ACCESSIONNAME\tSEQUENCE
#
#And divide the sequences into to two halves
#

import sys

file_path1 = raw_input("Please input formatted sequence file:") #ENTER FILEPATH OF FORMATTED SEQUENCE FILE

fastafile = open(file_path1, 'r') #OPEN SEQUENCE FILE

h1 = open('h1.txt', 'w') #CREATE EMPTY FILE FOR FIRST HALF OF SEQUENCE FILE
h2 = open('h2.txt', 'w') #CREATE EMPTY FILE FOR SECOND HALF OF SEQUENCE FILE
all = open('all.txt', 'w') #CREATE EMPTY FILE FOR ALL OF SEQUENCE FILE

from random import shuffle #IMPORT FUNCTION SHUFFLE FOR LATER 

i=0 #THIS WILL COUNT THE NUMBER OF SEQUENCES IN THE FILE

l=[] #THIS LIST WILL CONTAIN ALL ACCESSIONNAMES BEFORE THE TAB SEPARATION

d = {} #CREATE A DICTIONARY FOR SEQUENCE FILE

for line in fastafile:	#LOOP THROUGH THE LINES OF THE SEQUENCE FILE
	
	line = str.strip(line) #TURN EACH LINE INTO A STRING ITSELF
	
	(n,s) = line.split('\t') #LOG THE COMPONENTS OF EACH LINE SEPARATED BY TAB
	
	d[n] = (n,s) #MAKE ACCESSIONNAME AS THE KEY, AND ACCESSIONNAME AND SEQUENCE AS THE VALUES IN THE DICTIONARY
	
	l.append(n) #ALSO ADD THE ACCESSIONNAME TO THE LIST OF NAMES TO BE SHUFFLED
	
	i=i+1 #COUNT THE NUMBER OF SEQUENCES IN THE FILE

shuffle(l) #SHUFFLE THE LIST OF ACCESSIONNAMES

if (i%2==0): #IF THE NUMBER OF SEQUENCES IN FILE IS EVEN
	h=0.5*i #TAKE HALF OF THAT
	
else: #IF THE NUBMER OF SEQUENCES IN THE FILE IS ODD
	h=(i+1)/2 #ADD 1 TO SEQUENCE COUNT AND TAKE HALF OF THAT
	
h=int(h) #CHANGE THE H INTO AN INTEGER

for a in range(int(h)): #LOOP THROUGH THE FIRST HALF OF THE SHUFFLED LIST
	
	b=l[a] #GOING THROUGH THE SHUFFLED LIST ONE BY ONE
	
	h1.write(d[b][0]) #WRITE DOWN ACCESSIONNAME
	
	h1.write('\n') #CHANGE LINE
	
	h1.write(d[b][1]) #WRITE DOWN SEQUENCE OF THAT ACCESSIONNAME
	
	h1.write('\n') #CHANGE LINE
	
h1.close() #CLOSE FILE
		
for a in range(int(i-h)): #LOOP THROUGH THE SECOND HALF OF THE SHUFFLED LIST
	
	b=l[a+h] #GOING THROUGH THE SECOND HALF OF THE SHUFFLED LIST
	
	h2.write(d[b][0]) #WRITE DOWN CORRESPONDING ACCESSIONNAME
	
	h2.write('\n') #CHANGE LINE
	
	h2.write(d[b][1]) #WRITE DOWN SEQUENCE OF THE ACCESSIONNAME ABOVE
	
	h2.write('\n') #CHANGE LINE
	
h2.close()	#CLOSE FILE	

for a in range(i): #LOOP THROUGH THE FIRST HALF OF THE SHUFFLED LIST
	
	b=l[a] #GOING THROUGH THE SHUFFLED LIST ONE BY ONE
	
	all.write(d[b][0]) #WRITE DOWN ACCESSIONNAME
	
	all.write('\n') #CHANGE LINE
	
	all.write(d[b][1]) #WRITE DOWN SEQUENCE OF THAT ACCESSIONNAME
	
	all.write('\n') #CHANGE LINE
	
all.close() #CLOSE FILE		
		
		
		
		
